version: "3.3"
services:
  mpt-chat-gpt:
    container_name: mpt-chat-gpt
    build: .
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped # or "always"
    ports:
      - 8080:80
    command: /bin/sh -c "nginx -g 'daemon off;'"
networks:
    default:
        external:
                name: mephistonginx_mephisto-net